RDP_CONNECTION = {
    "name": "",
    "identifier": "",
    "parentIdentifier": "ROOT",
    "protocol": "rdp",
    "attributes": {
        "max-connections": "",
        "max-connections-per-user": "",
        "weight": "",
        "failover-only": "",
        "guacd-port": "",
        "guacd-encryption": "",
        "guacd-hostname": "",
    },
    "activeConnections": 0,
    "parameters": {
        "disable-audio": "",
        "server-layout": "",
        "domain": "",
        "hostname": "",
        "enable-font-smoothing": "",
        "security": "rdp",
        "port": "3389",
        "disable-auth": "",
        "ignore-cert": "",
        "console": "",
        "width": "",
        "height": "",
        "dpi": "",
        "color-depth": "",
        "console-audio": "",
        "enable-printing": "",
        "enable-drive": "",
        "create-drive-path": "",
        "enable-wallpaper": "",
        "enable-theming": "",
        "enable-full-window-drag": "",
        "enable-desktop-composition": "",
        "enable-menu-animations": "",
        "preconnection-id": "",
        "enable-sftp": "",
        "sftp-port": "",
    },
}